// FRONTEND/src/components/Hero/UrlForm.vue
<script setup lang="ts">
import { ref, reactive } from "vue";
import { Link2, ArrowRight } from "lucide-vue-next";
import Button from "../ui/Button/Button.vue";
import ShortenResult from "./ShortenResult.vue";
import { actions, isActionError, isInputError } from "astro:actions";

interface ActionState {
    error: string | null;
    data: {
        short_code: string;
        original_url: string;
        short_url: string;
        created_at: string;
        expires_at: string;
    } | null;
}

const url = ref("");
const isPending = ref(false);
const state = reactive<ActionState>({
    error: null,
    data: null,
});

const handleSubmit = async () => {
    if (!url.value.trim() || isPending.value) return;

    isPending.value = true;
    state.error = null;
    state.data = null;

    try {
        const { data, error } = await actions.shortenUrl({ url: url.value });

        if (error) {
            state.error = isInputError(error)
                ? (error.fields.url?.[0] ?? "Invalid input")
                : isActionError(error)
                  ? error.message
                  : "An unexpected error occurred";
        } else if (data) {
            state.data = data;
            url.value = "";
        }
    } catch (e) {
        state.error = "Failed to connect to the server";
    } finally {
        isPending.value = false;
    }
};
</script>

<template>
    <div class="w-full max-w-xl">
        <form
            @submit.prevent="handleSubmit"
            class="group relative flex items-center rounded-xl border border-border bg-card p-1.5 transition-all focus-within:border-primary/50"
        >
            <label for="url-input" class="sr-only">
                Enter the long URL to shorten
            </label>

            <Link2
                class="ml-3 h-4 w-4 shrink-0 text-muted-foreground"
                aria-hidden="true"
            />

            <input
                id="url-input"
                v-model="url"
                type="text"
                placeholder="Paste your long URL here..."
                required
                class="flex-1 bg-transparent px-3 py-2.5 text-sm focus:outline-none"
                :aria-invalid="!!state.error"
                :aria-describedby="state.error ? 'url-error' : undefined"
            />

            <Button
                type="submit"
                variant="rust"
                class="cursor-pointer"
                :disabled="isPending || !url.trim()"
            >
                <template v-if="isPending">
                    <span class="animate-pulse">Shortening...</span>
                </template>
                <template v-else>
                    <span class="hidden sm:inline">Shorten</span>
                    <ArrowRight class="h-3.5 w-3.5 ml-2" aria-hidden="true" />
                </template>
            </Button>
        </form>

        <transition
            enter-active-class="transition duration-200 ease-out"
            enter-from-class="transform -translate-y-2 opacity-0"
            enter-to-class="transform translate-y-0 opacity-100"
            leave-active-class="transition duration-150 ease-in"
            leave-from-class="opacity-100"
            leave-to-class="opacity-0"
        >
            <p
                v-if="state.error"
                id="url-error"
                role="alert"
                class="mt-2 text-sm text-red-500 font-medium"
            >
                {{ state.error }}
            </p>
        </transition>

        <transition
            enter-active-class="transition duration-300 ease-out"
            enter-from-class="transform translate-y-4 opacity-0"
            enter-to-class="transform translate-y-0 opacity-100"
        >
            <div v-if="state.data" class="mt-6">
                <ShortenResult
                    :shortenedLink="state.data.short_url"
                    :originalUrl="state.data.original_url"
                />
            </div>
        </transition>
    </div>
</template>

// FRONTEND/src/components/Hero/UrlForm.tsx
import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Link2, ArrowRight, Check, Copy, BarChart3 } from "lucide-react";
import { Button } from "../ui/Button/Button";

export default function UrlForm() {
  const [url, setUrl] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [shortenedLink, setShortenedLink] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleShorten = async () => {
    setIsLoading(true);
    // Simulación de lógica de backend en Rust
    setTimeout(() => {
      setShortenedLink("short.it/xyz123");
      setIsLoading(false);
    }, 1000);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(shortenedLink || "");
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full max-w-xl">
      <div className="group relative flex items-center rounded-xl border border-border bg-card p-1.5 transition-all focus-within:border-primary/50">
        <Link2 className="ml-3 h-4 w-4 shrink-0 text-muted-foreground" />
        <input
          type="url"
          placeholder="Paste your long URL here..."
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          className="flex-1 bg-transparent px-3 py-2.5 text-sm focus:outline-none"
        />
        <Button
          className="cursor-pointer"
          onClick={handleShorten}
          disabled={isLoading || !url.trim()}
        >
          {isLoading ? (
            "..."
          ) : (
            <>
              <span className="hidden sm:inline">Shorten</span>{" "}
              <ArrowRight className="h-3.5 w-3.5" />
            </>
          )}
        </Button>
      </div>

      <AnimatePresence>
        {shortenedLink && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mt-6 glass rounded-xl p-5 border border-primary/20"
          >
            <div className="flex items-center justify-between gap-4">
              <div className="min-w-0 flex-1">
                <p className="truncate text-sm font-semibold text-primary">
                  {shortenedLink}
                </p>
                <p className="truncate text-xs text-muted-foreground">{url}</p>
              </div>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" onClick={copyToClipboard}>
                  {copied ? (
                    <Check className="h-3.5 w-3.5" />
                  ) : (
                    <Copy className="h-3.5 w-3.5" />
                  )}
                </Button>
                <Button variant="ghost" size="sm">
                  <BarChart3 className="h-3.5 w-3.5" />
                </Button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
